### ISSUE TITLE
algoliasearch/lite and server-side rendering

### ISSUE THREAD

**Issue by vslio** [algolia/algoliasearch-client-javascript#283]
Hello!

I'm currently working on a React application which supports server-side/universal rendering. Importing the lite version of algoliasearch leads to a `ReferenceError: window is not defined` error (wrong module.exports?). However, importing the full version of algoliasearch, ie: `import search from 'algoliasearch'` works perfectly.

**Comment by vvo** [comment]
Fixed, released in 3.15.1

**Comment by ramusus** [comment]
@vvo @vslio I still have this issue during server rendering. I tried 3.15.1 and 3.18.1 lite and full versions with no any success.
I call search() method inside render():

```
import algoliasearch from 'algoliasearch/lite';
...

  search(theQuery, isNewQuery) {
    const algClient = algoliasearch(this.props.algoliasearch.applicationID, this.props.algoliasearch.apiKey);
    const algIndex = algClient.initIndex(...);
    algIndex.search(theQuery, (err, content) => {
    ...
    } 
  }
```

and looking into source I get 

    ReferenceError: window is not defined

What I'm doing wrong?

**Comment by vvo** [comment]
Do you think you can either get a more precise stack trace or maybe a simple github project reproducing the issue so we can wokr on it?

**Comment by zaihuaone** [comment]
Have been built, and linked to other pages. URL: www.zaihuaone.com

**Comment by zaihuaone** [comment]
http://oodusa5do.bkt.clouddn.com/1O@X0UPZS%29PYUN%60DIO1%7BI84.png

I open the permanent link is this, it should be www.zaihuaone.com)

**Comment by vvo** [comment]
Hi @zaihuaone I will need a GitHub repo reproducing this issue to be able to work on it. Right now it's too vague and so I cannot help you in the good conditions.

I need to be able to reproduce you errors on my computer to be able to help you.

**Comment by reohjs** [comment]
Ran into this recently.. fixed it by using `target: 'node'` config in my server-side webpack: https://github.com/kriasoft/react-starter-kit/issues/1218#issuecomment-293224878

**Comment by Haroenv** [comment]
Thanks for telling how you solved it @reohjs!

**Comment by Haroenv** [comment]
seeing as it's solved with the comment @reohjs made, feel free to make a new issue if you're also having this problem because of another or the same reason.
