### ISSUE TITLE
Bug: aroundRadius: 'all' breaks facets

### ISSUE THREAD

**Issue by rscotten** [algolia/algoliasearch-client-javascript#782]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When submitting a search query with the following query params:

```javascript
{
  aroundLatLng: '34.1657, -118.3409',
  aroundRadius: 'all',
  facets: ['*'],
}
```

The response includes an empty object for the `facets`.

If removing the `aroundRadius: 'all'` from the query like so, the facets are returned in the response as expected.

```javascript
{
  aroundLatLng: '34.1657, -118.3409',
  facets: ['*'],
}
```

**What is the expected behavior?**

This request should return the facets in the response.  It was working a few days ago, it must have just broke.

```javascript
{
  aroundLatLng: '34.1657, -118.3409',
  aroundRadius: 'all',
  facets: ['*'],
}
```

**Comment by Haroenv** [comment]
I can reproduce this: https://codesandbox.io/s/javascript-client-app-6tsvv and have contacted the API team to see if this is a recent regression. Thanks!

**Comment by rscotten** [comment]
Looks like it's fixed now.  Thanks!

**Comment by Haroenv** [comment]
I'm still seeing the same behaviour not working, but I'd guess you solved this another way

**Comment by rscotten** [comment]
@Haroenv ugh, yeah, you're right

**Comment by rscotten** [comment]
@Haroenv for now I'm just replacing a radius of `all` with `20000000`, which is about half the circumference of Earth in meters.

**Comment by Haroenv** [comment]
Hi @rscotten, I've just gotten confirmation that this is a regression, and not a purposeful change. A Pull Request for fixing it is in the works. I'm glad you have a workaround!

**Comment by Haroenv** [comment]
This has been fixed in the API now, so it's a question of days before it's released. I'll close this issue now, even if it can still take some time before it propagates to your server. Don't hesitate to reopen if this isn't fixed in a few days.
